services:
  - type: web
    name: histeeria-lite
    env: docker
    plan: free
    region: oregon
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
